:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= Spring Boot 2Showcase
Ron Kurr <rkurr@jvmguy.com>

toc::[]

== Overview
This project is an opinionated view on how to construct a Spring Boot 2 REST service.  In this template, we will use the non-reactive form of HTTP management and the Groovy programming language.  Other templates will showcase the reactive forms and the Kotlin programming language. The assumption is that the service will be run in the cloud, likely in a Docker container, so we configure the service to provide distributed logging and telemetry.

== Prerequisites
* http://zulu.org/[Java 8] installed and working

== Building
== Installation
== Tips and Tricks
=== Service Configuration
The service's configuration is held in `ApplicationProperties` and is configured to apply validation rules at startup, ensuring that the required information is provided.  The values are specified in `application.yml`.

=== Profiles
The service is configured to support 3 profiles:
* development (default)
* test
* production

== Troubleshooting
== Change History
== License and Credits
This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
