:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= Spring Boot 2Showcase
Ron Kurr <rkurr@jvmguy.com>

toc::[]

== Overview
This project is an opinionated view on how to construct a Spring Boot 2 REST service.  In this template, we will use the non-reactive form of HTTP management and the Groovy programming language.  Other templates will showcase the reactive forms and the Kotlin programming language. The assumption is that the service will be run in the cloud, likely in a Docker container, so we configure the service to provide distributed logging and telemetry.

== Prerequisites
* http://zulu.org/[Java 8] installed and working

== Building
== Installation
== Tips and Tricks
=== Service Configuration
The service's configuration is held in `ApplicationProperties` and is configured to apply validation rules at startup, ensuring that the required information is provided.  The values are specified in `application.yml`.

=== Profiles
The service is configured to support 3 profiles:

* development (default)
* test
* production

=== Actuator Endpoints
By default, all endpoints are exposed over HTTP.  You might want to trim that list down for the production profile.  The endpoints base path is `/operations` and not the usual `/actuator`.

=== Info Endpoint
The info endpoint has been configured to provide Operations with various pieces of potentially useful information.

----
{
    "git": {
        "branch": "master",
        "commit": {
            "id": "16a7b87",
            "time": "2018-03-12T20:01:24Z"
        }
    },
    "java-runtime": {
        "vendor": "Azul Systems, Inc.",
        "version": "1.8.0_162"
    },
    "operating-system": {
        "architecture": "amd64",
        "name": "Linux",
        "version": "4.4.0-112-generic"
    },
    "service": {
        "description": "Provides a REST API using a non-reactive programming model.",
        "name": "rest-service",
        "version": "0.0.0-SNAPSHOT"
    },
    "user": {
        "home-directory": "/home/vagrant",
        "name": "vagrant",
        "working-directory": "/home/vagrant/GitHub/spring-boot-mvc-groovy-showcase"
    }
}
----

=== Prometheus Endpoint
https://prometheus.io/[Prometheus] can configured to poll the `/operations/prometheus` endpoint, providing insight into the service's internals and JVM.

=== Structured Logging
The service has been configured to use a https://github.com/logstash/logstash-logback-encoder[Logback JSON encoder] that emits logs in a structured format that easily be parsed by Logstash and other distributed logging stacks.  Edit `logback-logstash.xml` to alter the format.

----
{
  "timestamp": "2018-03-12T20:29:17.945+00:00",
  "message": "Started Application in 2.578 seconds (JVM running for 3.034)",
  "component": "com.example.nonreactive.Application",
  "level": "INFO"
}
----

=== Auto-configured Tests
There are samples of how to create auto-configured tests, which only test a "slice" of the application.
* REST client test
* Web MVC test
* REST documentation test

== Troubleshooting
== Change History
== License and Credits
This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
