:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= Spring Boot 2 Showcase
Ron Kurr <rkurr@jvmguy.com>

toc::[]

== Overview
This project is an opinionated view on how to construct a Spring Boot 2 REST service.  In this template, we will use the non-reactive form of HTTP management and the Groovy programming language.  Other templates will showcase the reactive forms and the Kotlin programming language. The assumption is that the service will be run in the cloud, likely in a Docker container, so we configure the service to provide distributed logging and telemetry.

== Prerequisites
* http://zulu.org/[Java 8] installed and working

== Building
=== Version Overrides
If you don't like the version of a dependency that Spring is pulling in, you can override it.  Look at the https://github.com/spring-projects/spring-boot/blob/v2.0.0.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml[BOM file] to determine which property to set and specify your own version in `gradle.properties`.

----
groovy.version = 2.4.14
mssql-jdbc.version = 6.2.2.jre8
----

== Installation
== Tips and Tricks
=== Profile-specific Logging
Look at `logback-spring.xml` so see how to specify different logging levels based on the active Spring profile.  The expressions can get sophisticated but this sample tones down the message level as we approach the production profile.

=== Dynamic Logging Configuration
Aspects of the logging configuration can be provided at launch-time via the Spring environment.  Look at `logback-spring.xml` and how the `queueSize` property is derived fom the `application.yml` file.

=== Package Layout
The Spring documentation suggest grouping your files by "feature", making it easier to extract logic into microservices later.

----
com
 +- example
     +- myapplication
         |
         +- Application.java
         +- WebConfiguration.java
         +- PersistenceConfiguration.java
         |
         +- shared
         |   +- ApplicationProperties.java
         |
         +- customer
         |   +- Customer.java
         |   +- CustomerController.java
         |   +- CustomerService.java
         |   +- CustomerRepository.java
         |
         +- order
             +- Order.java
             +- OrderController.java
             +- OrderService.java
             +- OrderRepository.java
----

=== Service Configuration
The service's configuration is held in `ApplicationProperties` and is configured to apply validation rules at startup, ensuring that the required information is provided.  The values are specified in `application.yml`.

=== Profiles
The service is configured to support 3 profiles:

* development (default)
* test
* production

=== Actuator Endpoints
By default, all endpoints are exposed over HTTP.  You might want to trim that list down for the production profile.  The endpoints base path is `/operations` and not the usual `/actuator`.

=== Info Endpoint
The info endpoint has been configured to provide Operations with various pieces of potentially useful information.

----
{
    "git": {
        "branch": "master",
        "commit": {
            "id": "16a7b87",
            "time": "2018-03-12T20:01:24Z"
        }
    },
    "java-runtime": {
        "vendor": "Azul Systems, Inc.",
        "version": "1.8.0_162"
    },
    "operating-system": {
        "architecture": "amd64",
        "name": "Linux",
        "version": "4.4.0-112-generic"
    },
    "service": {
        "description": "Provides a REST API using a non-reactive programming model.",
        "name": "rest-service",
        "version": "0.0.0-SNAPSHOT"
    },
    "user": {
        "home-directory": "/home/vagrant",
        "name": "vagrant",
        "working-directory": "/home/vagrant/GitHub/spring-boot-mvc-groovy-showcase"
    }
}
----

=== Prometheus Endpoint
https://prometheus.io/[Prometheus] can configured to poll the `/operations/prometheus` endpoint, providing insight into the service's internals and JVM.

.prometheus.yml
----
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring'
    metrics_path: '/operations/prometheus'
    static_configs:
        - targets: ['localhost:8080']
----

=== RestTemplate Metrics
The outbound gateway in the sample uses the `RestTemplateBuilder` which produces a `RestTemplate` that emits metric data.  In the Prometheus console, you will see something like this:

.Sample Prometheus Console Output
----
http_client_requests_seconds_count{clientName="randomuser.me",instance="localhost:8080",job="spring",method="GET",status="200",uri="/api?seed={userID}"}	625
----

=== Counters and Gages
The `InboundGateway` shows how to construct a `Counter` that can be used in metrics collection and analysis.

=== Structured Logging
The service has been configured to use a https://github.com/logstash/logstash-logback-encoder[Logback JSON encoder] that emits logs in a structured format that easily be parsed by Logstash and other distributed logging stacks.  Edit `logback-logstash.xml` to alter the format.

----
{
  "timestamp": "2018-03-12T20:29:17.945+00:00",
  "message": "Started Application in 2.578 seconds (JVM running for 3.034)",
  "component": "com.example.nonreactive.Application",
  "level": "INFO"
}
----

=== Profile-specific Logging
Edit the `logback-spring.xml` file to use different logging levels based on the active profiles.

.logback-spring.xml
----
    <springProfile name="default">
        <logger name="com.example" level="ALL"/>
        <logger name="org.springframework" level="INFO"/>
        <logger name="org.springframework.web.client.RestTemplate" level="ALL"/>
    </springProfile>

    <springProfile name="test">
        <logger name="com.example" level="INFO"/>
        <logger name="org.springframework" level="INFO"/>
    </springProfile>

    <springProfile name="production">
        <logger name="com.example" level="WARN"/>
        <logger name="org.springframework" level="WARN"/>
    </springProfile>
----

=== Auto-configured Tests
There are samples of how to create auto-configured tests, which only test a "slice" of the application.

* REST client test
* Web MVC test
* REST documentation test
* JSON test

=== REST Template Interception
Look at `OutboundGateway` to see how the `RestTemplateBuilder` can be used to install a custom interceptor where you can add in custom logging and metrics.

=== Custom Operations Endpoint
Look at `CustomActuator` to see an example of custom endpoint intended for Operations.  These could be used for "deep" health checks, synthetic transactions, etc.

.http --verbose localhost:8080/operations/deep-health
----
GET /operations/deep-health HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.9



HTTP/1.1 200
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Wed, 21 Mar 2018 16:13:55 GMT
Transfer-Encoding: chunked

{
    "status": "Looking good"
}
----

=== Custom Health Indicator
Look at `GoogleHealthIndicator` for an example on how to write a custom health indicator.  All it does ensure that Google can be contacted.  This is useful to check the health of downstream services that aren't covered out of the box.

.http localhost:8080/operations/health
----
HTTP/1.1 200
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Wed, 21 Mar 2018 17:41:46 GMT
Transfer-Encoding: chunked

{
    "details": {
        "diskSpace": {
            "details": {
                "free": 111565172736,
                "threshold": 10485760,
                "total": 132371533824
            },
            "status": "UP"
        },
        "google": {
            "details": {
                "latency (ms)": 81
            },
            "status": "UP"
        }
    },
    "status": "UP"
}
----

=== Custom Exception Handler
Look at `CustomExceptionHandler` for an example of how to ensure all exceptions are transformed into the hypermedia control.

.http  localhost:8080/instance
----
HTTP/1.1 500
Connection: close
Content-Encoding: gzip
Content-Type: application/json;charset=UTF-8
Date: Wed, 21 Mar 2018 19:34:25 GMT
Transfer-Encoding: chunked
Vary: Accept-Encoding

{
    "error": {
        "developer-message": "uri=/instance;client=127.0.0.1",
        "message": "Forced to fail!"
    }
}
----

=== XML Support
For the price of including an extra library, the inbound gateway supports rending the hypermedia control in XML form.

.curl  --header "Accept:application/xml" localhost:8080/user/bob
----
<HypermediaControl>
  <user-information>
    <username>whitelion877</username>
    <e-mail>eevi.toivonen@example.com</e-mail>
  </user-information>
</HypermediaControl>
----

=== Changing Logging Levels Dynamically
Using REST calls, you can change the logging levels of the application dynamically.

.To get a list of all loggers
----
http GET localhost:8080/operations/loggers

{
  "levels" : [ "OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE" ],
  "loggers" : {
    "ROOT" : {
      "configuredLevel" : "WARN",
      "effectiveLevel" : "WARN"
    },
    "com" : {
      "effectiveLevel" : "WARN"
    },
    "com.example" : {
      "configuredLevel" : "TRACE",
      "effectiveLevel" : "TRACE"
    },
    "com.example.nonreactive" : {
      "configuredLevel" : "DEBUG",
      "effectiveLevel" : "DEBUG"
    },
    ...
}
----

.To get the current level for a specific logger
----
http GET localhost:8080/operations/loggers/com.example.nonreactive

HTTP/1.1 200
Content-Disposition: inline;filename=f.txt
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Wed, 21 Mar 2018 20:07:04 GMT
Transfer-Encoding: chunked

{
    "configuredLevel": "DEBUG",
    "effectiveLevel": "DEBUG"
}
----

.To change the level for a specific logger
----
http POST localhost:8080/operations/loggers/com.example.nonreactive configuredLevel=TRACE

HTTP/1.1 204
Date: Wed, 21 Mar 2018 20:07:46 GMT
----

=== JPA Support
Look at `UserRepositoryIntegrationTest` for an example of how to test a JPA repository.  The application is configured to use an in-memory database so don't expect things to persist once you shutdown the application.  Look at `ProductionProcessor` to see how the gateway is used from core.

=== MongoDB Support
Look at `VehicleRepositoryIntegrationTest` for an example of how to test a document repository.  The application is configured to use an in-memory database so don't expect things to persist once you shutdown the application.  Look at `ProductionProcessor` to see how the gateway is used from core.

=== Redis Support
Look at `ContactRepositoryIntegrationTest` for an example of how to test a key-value repository.  Unlike some of the other test, a local instance of Redis must be running in order for the test to work.  Look at `ProductionProcessor` to see how the gateway is used from core.

=== Caching Support
Look at `UserPort` for an example of how to enable caching.  Look at `application.yml` to see how we force the selection of the in-memory cache implementation, otherwise Redis would've been selected.

=== Custom Metrics
Look at `ProductionProcessor` for an example of how to record how long it takes for a service to run.  In this example we time things by hand but you could imagine using aspects to automatically wrap interesting parts of the code.

.http localhost:8080/operations/metrics/service-timer
----
HTTP/1.1 200
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Fri, 23 Mar 2018 19:11:23 GMT
Transfer-Encoding: chunked

{
    "availableTags": [
        {
            "tag": "layer",
            "values": [
                "core"
            ]
        }
    ],
    "measurements": [
        {
            "statistic": "COUNT",
            "value": 49.0
        },
        {
            "statistic": "TOTAL_TIME",
            "value": 1.458764845
        },
        {
            "statistic": "MAX",
            "value": 1.128834074
        }
    ],
    "name": "service-timer"
}
----

== Troubleshooting
=== Cannot Connect To Redis
Unfortunately, we are not using an embedded version of Redis, so you must be running a local instance in order for things to work.  The https://hub.docker.com/_/redis/[Docker container] is probably the simplest way to do so.

== Change History
== License and Credits
This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
