---
com:
    example:
        instance: ${random.uuid}
        nested:
            location: https://example.com/
spring:
    profiles: default
server:
    port: 8000

---
spring:
    profiles: test
server:
    port: 9000

---
spring:
    profiles: production
server:
    port: 0
