---
info:
    service:
        name: ${name}
        description: ${description}
        version: ${version}
service:
 # these work fine from the command-line but puke in IDEA
 #   instance: \${random.uuid}
 #   timeout: \${random.int[10,60]}s
    nested:
        location: https://example.com/
    logging:
        queueSize: 2048
spring:
    profiles: default
    cache:
        type: simple
    data:
        neo4j:
            embedded:
                enabled: true
    jackson:
        serialization:
            indent_output: true
        default-property-inclusion: non_empty
    jpa:
        hibernate:
            ddl-auto: create-drop
    main:
        banner-mode: "off"

server:
    compression:
        enabled: true
        mime-types: "application/json,application/hal+json"
        min-response-size: 512
    port: 8080
    servlet:
        context-path: /
    tomcat:
        accesslog:
            enabled: false
    use-forward-headers: true

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /operations
---
spring:
    profiles: test
management:
    endpoint:
        health:
            show-details: when-authorized
server:
    port: 9000

---
spring:
    profiles: production
management:
    endpoint:
        health:
            show-details: never
server:
    port: 0
