---
info:
    service:
        name: ${name}
        description: ${description}
        version: ${version}
service:
 # these work fine from the command-line but puke in IDEA
 #   instance: \${random.uuid}
 #   timeout: \${random.int[10,60]}s
    nested:
        location: https://example.com/
spring:
    profiles: default
    jackson:
        serialization:
            indent_output: true
        default-property-inclusion: non_empty
server:
    port: 8000
management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /operations

---
spring:
    profiles: test
server:
    port: 9000

---
spring:
    profiles: production
server:
    port: 0
