---
info:
    service:
        name: ${name}
        description: ${description}
        version: ${version}
service:
    instance: \${random.uuid}
    timeout: \${random.int[10,60]}s
    nested:
        location: https://example.com/
spring:
    profiles: default
server:
    port: 8000

---
spring:
    profiles: test
server:
    port: 9000

---
spring:
    profiles: production
server:
    port: 0
